### ISSUE TITLE
Uncaught ReferenceError: admob is not defined 

### ISSUE THREAD

**Issue by prantikv** [appfeel/admob-google-cordova#9]
hi i am using ur plugin and it has been working great for me.
However i recently got a bug, i get an js error saying   "Uncaught ReferenceError: admob is not defined " and the line which is getting the error is if(admob)

Let me make it clear that it doesn't happen all the time 99.99% of the time it works..it only happens sometimes. 

what i don't understand is that if admob is undefined then it should evaluate to false and go to the else but it shows the error. 

similar issue is here but it was asked for the incorrect plugin:
https://github.com/floatinghotpot/cordova-plugin-admob/issues/177

       function initAds() {
              if (admob) {
                var adPublisherIds = {
                  ios : {
                    banner : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx",
                    interstitial : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx"
                  },
                  android : {
                    banner : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx",
                    interstitial : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx"
                  }
                };

                var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;

                admob.setOptions({
                  publisherId: admobid.banner,
                  interstitialAdId: admobid.interstitial
                });

                registerAdEvents();

              } else {
                alert('AdMobAds plugin not ready');
              }
            }

      initAds();

      // display a banner at startup
      admob.createBannerView();

      // request an interstitial
      admob.requestInterstitialAd();

Kindly let me know when u get around this...thanks

**Comment by appfeel** [comment]
Hi @prantikv, thanks for the comments.
I will update the documentation (this is just a workaround, is not solving the error when it appears) replacing `if (admob)` by `if (window.admob)`:

```javascript
   function initAds() {
          if (window.admob) {
            var adPublisherIds = {
              ios : {
                banner : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx",
                interstitial : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx"
              },
              android : {
                banner : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx",
                interstitial : "ca-app-pub-xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxx"
              }
            };

            var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;

            admob.setOptions({
              publisherId: admobid.banner,
              interstitialAdId: admobid.interstitial
            });

            registerAdEvents();

          } else {
            alert('AdMobAds plugin not ready');
          }
        }

  initAds();

  if (window.admob) {
    // display a banner at startup
    admob.createBannerView();

    // request an interstitial
    admob.requestInterstitialAd();
  }
```

Normally this error can happen because of different reasons:

* The app is running in an emulator, not in a real device: plugins don't work in emulators (yet)
* There is another plugin that is breaking other plugins (really strange)
* Not all the dependencies needed by the plugin are ready and updated

I would recommend:

* Get the list of installed plugins `cordova plugin ls`
* Remove every plugin with `cordova plugin rm ...`
* Remove every platform with `cordova platform rm ios` (android, wp8, etc...)
* Delete all cached plugins from /Users/<username>/.plugman/cache/*
* Add all plugins again
* Add all platforms again

**Comment by appfeel** [comment]
Hi @prantikv,
Please, could you confirm that this is not repeating anymore? Thanks.

**Comment by prantikv** [comment]
yes thanks now it has been solved..

**Comment by nnarasimha** [comment]
I am using ionic and tried to your plugin. However it fails to resolve window.AdMob. Any suggestions what could be going on?

Thanks
--Narasimha

**Comment by appfeel** [comment]
It seems the variable name is not correct, should be `window.admob` lowercase. If still not working, I suggest to clean your plugin cache, remove the plugin and install it again:

```
cordova plugin rm com.admob.google
cordova plugin rm cordova-admob
rm -rf /Users/<your user>/.plugman/cache
rm -rf /Users/<your user>/.npm/cordova-*
cordova plugin add cordova-admob
```

**Comment by nikhilknoldus** [comment]
After doing everything, your code isn't working at all, i have used typescript (becase i don't why you have not written it in typecript, angular 2 and ionic 2 is best compatible with typescript, still)


> EXCEPTION: Error: Uncaught (in promise): ReferenceError: AdMob is not definedBrowserDomAdapter.logError @ browser_adapter.js:77BrowserDomAdapter.logGroup @ browser_adapter.js:87ExceptionHandler.call @ exception_handler.js:57(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
> browser_adapter.js:77 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:59(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
> browser_adapter.js:77 Error: Uncaught (in promise): ReferenceError: AdMob is not defined
>     at resolvePromise (zone.js:538)
>     at zone.js:574
>     at ZoneDelegate.invokeTask (zone.js:356)
>     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:36)
>     at ZoneDelegate.invokeTask (zone.js:355)
>     at Zone.runTask (zone.js:256)
>     at drainMicroTaskQueue (zone.js:474)
>     at HTMLButtonElement.ZoneTask.invoke (zone.js:426)BrowserDomAdapter.logError @ browser_adapter.js:77ExceptionHandler.call @ exception_handler.js:60(anonymous function) @ application_ref.js:265schedulerFn @ async.js:123SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:112NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.js:120NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.js:66ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
> zone.js:461 Unhandled Promise rejection: AdMob is not defined ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: AdMob is not defined(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
> zone.js:463 Error: Uncaught (in promise): ReferenceError: AdMob is not defined(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426


I have done everything you told me, my code is that i have written in page1.ts (using sidemenu template)


`import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import {StatusBar} from 'ionic-native';

declare var AdMob: any;

@Component({
  templateUrl: 'build/pages/page1/page1.html'
})
export class Page1 {

 private admobId: any;

 constructor(private navController: NavController, private platform: Platform) {
         this.platform = platform;
         if(/(android)/i.test(navigator.userAgent)) {
             this.admobId = {
                 banner: 'ca-app-pub-5724383886840960/6005198717 ',
                 interstitial: 'ca-app-pub-jjj/kkk'
             };
         } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
             this.admobId = {
                 banner: 'ca-app-pub-5724383886840960/6005198717 ',
                 interstitial: 'ca-app-pub-ppp/zzz'
             };
         }
     } createBanner() {
        this.platform.ready().then(() => {
            if(AdMob) {
                AdMob.createBanner({
                    adId: this.admobId.banner,
                    autoShow: false
                });
            }
        });
    }

    showInterstitial() {
        this.platform.ready().then(() => {
            if(AdMob) {
                AdMob.prepareInterstitial({
                    adId: this.admobId.interstitial,
                    autoShow: true
                });
            }
        });
    }

    showBanner(position) {
        this.platform.ready().then(() => {
            if(AdMob) {
                var positionMap = {
                    "bottom": AdMob.AD_POSITION.BOTTOM_CENTER,
                    "top": AdMob.AD_POSITION.TOP_CENTER
                };
                AdMob.showBanner(positionMap[position.toLowerCase()]);
            }
        });
    }

    hideBanner(position) {
        this.platform.ready().then(() => {
            if(AdMob) {
                AdMob.hideBanner();
            }
        });
    }
}
`

**Comment by miqmago** [comment]
Please try with:

```js
import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import {StatusBar} from 'ionic-native';

declare var admob: any;

@Component({
  templateUrl: 'build/pages/page1/page1.html'
})
export class Page1 {

    private admobId: any;

    constructor(private navController: NavController, private platform: Platform) {
         this.platform = platform;
         if(/(android)/i.test(navigator.userAgent)) {
             this.admobId = {
                 banner: 'ca-app-pub-5724383886840960/6005198717 ',
                 interstitial: 'ca-app-pub-jjj/kkk'
             };
         } else if(/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {
             this.admobId = {
                 banner: 'ca-app-pub-5724383886840960/6005198717 ',
                 interstitial: 'ca-app-pub-ppp/zzz'
             };
         }
    } 

    createBanner() {
        this.platform.ready().then(() => {
            if (window.admob) {
                admob.createBanner({
                    adId: this.admobId.banner,
                    autoShow: false
                });
            }
        });
    }

    showInterstitial() {
        this.platform.ready().then(() => {
            if (window.admob) {
                admob.prepareInterstitial({
                    adId: this.admobId.interstitial,
                    autoShow: true
                });
            }
        });
    }

    showBanner(position) {
        this.platform.ready().then(() => {
            if (window.admob) {
                var positionMap = {
                    "bottom": admob.AD_POSITION.BOTTOM_CENTER,
                    "top": admob.AD_POSITION.TOP_CENTER
                };
                admob.showBanner(positionMap[position.toLowerCase()]);
            }
        });
    }

    hideBanner(position) {
        this.platform.ready().then(() => {
            if (window.admob) {
                admob.hideBanner();
            }
        });
    }
}
```

This is written in js to support angular 1/ionic 1. At the end, when you compile your app, you still get js :)

**Comment by golusuresh1234** [comment]
after open the app its showing object #<object> has no method 'setoptions' . how to solve this issue.
